---
- name: Play - Anosther Register Example
  hosts: planet-express
  gather_facts: true

  tasks:
          - name: Reachout with geturl to random generation
            get_url:
                    url: https://www.random.org/integers/?num=1&min=0&max=1&col=1&base=10&format=plain&rnd=new
                    dest: ~/rand.txt
                    force: yes
          - name: Read the rand.txt and save results in rendvarz
            command: cat ~/rand.txt
            register: randvarz

          - name: "debug - display the ansible was: {{ randvarz.stdout }}"
            debug:
                    msg: " The value returned to ansible was: {{ randvarz.stdout }}"

